version: '3'

networks:
  internal:

services:
  mongo:
    networks:
      - internal
    image: 'mongo:4.4.6'
    container_name: 'mongo'
    ports:
      - '27017:27017'
  GraphQL-project:
    build : .
    env_file:
      - ./.env
    volumes:
      - ./:/app
    networks:
      - internal